apiVersion: v1
kind: Pod
metadata:
  name: my-python-app-pod
spec:
  containers:
  - image: 983372048879.dkr.ecr.us-east-1.amazonaws.com/clo835-assigmt2-repo:my_app_img
    name: python-container
    resources: {}
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: "blue"
    - name: DBHOST
      value: kubectl get pod mkubectl get pod mysql-pod --namespace=mysqlpod-namespace -o jsonpath='{.status.podIP}'
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "db_pass123"
 dnsPolicy: ClusterFirst
 restartPolicy: Always
 imagePullSecrets:
    - name: regcred
status: {}



