apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 983372048879.dkr.ecr.us-east-1.amazonaws.com/clo835-assigmt2-repo:my_db_img
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: db_pass12
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
    status: {}
