apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: employees
spec:
  type: NodePort
  selector:
    app: employees
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000